# Generated by Django 5.2.15 on 2026-08-14 14:40

import django.db.models.deletion
import django_mongodb_backend.fields
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BodyAnalysisHistory',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('analysis_method', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=20)),
                ('body_shape', models.CharField(max_length=50)),
                ('confidence_score', models.FloatField()),
                ('measurements', models.JSONField(blank=True, null=True)),
                ('image_url', models.CharField(blank=True, max_length=500, null=True)),
                ('fashion_recommendations', models.JSONField(default=list)),
                ('complete_ai_response', models.JSONField(default=dict)),
                ('version', models.CharField(default='1.0', max_length=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='body_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='ColorAnalysisHistory',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('undertone', models.CharField(max_length=50)),
                ('season', models.CharField(max_length=50)),
                ('best_colors', models.JSONField(default=list)),
                ('avoid_colors', models.JSONField(default=list)),
                ('neutral_colors', models.JSONField(default=list)),
                ('accent_colors', models.JSONField(default=list)),
                ('color_palette', models.JSONField(default=list)),
                ('image_url', models.CharField(blank=True, max_length=500, null=True)),
                ('complete_ai_response', models.JSONField(default=dict)),
                ('version', models.CharField(default='1.0', max_length=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='color_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='UserToken',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(default=uuid.uuid4, max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tokens', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
