# Generated by Django 5.2.15 on 2026-08-14 11:14

import body_analysis.models
import django.db.models.deletion
import django_mongodb_backend.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BodyAnalysisRecord',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(default='female', max_length=20)),
                ('bust_inches', models.FloatField(blank=True, null=True)),
                ('waist_inches', models.FloatField(blank=True, null=True)),
                ('hip_inches', models.FloatField(blank=True, null=True)),
                ('high_hip_inches', models.FloatField(blank=True, null=True)),
                ('predicted_shape', models.CharField(max_length=50)),
                ('confidence', models.FloatField(default=0.95)),
                ('recommendations', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='body_analyses', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BodyAnalysis',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=body_analysis.models.upload_path)),
                ('landmarks', models.JSONField(blank=True, help_text='Raw pose landmarks from MediaPipe/Detectron2.', null=True)),
                ('features', models.JSONField(blank=True, help_text='Engineered proportional features fed to the classifier.', null=True)),
                ('measurements', models.JSONField(blank=True, help_text='Derived shoulder/waist/hip/symmetry metrics (pixel-normalized).', null=True)),
                ('predicted_shape', models.CharField(blank=True, max_length=32)),
                ('confidence', models.FloatField(blank=True, null=True)),
                ('probabilities', models.JSONField(blank=True, help_text='Per-class probability distribution.', null=True)),
                ('status', models.CharField(choices=[('pending', 'pending'), ('done', 'done'), ('failed', 'failed')], default='pending', max_length=16)),
                ('error', models.TextField(blank=True)),
                ('processing_ms', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analyses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='body_analys_user_id_03ece8_idx')],
            },
        ),
    ]
