# Generated by Django 5.2.15 on 2026-08-08 17:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BodyAnalysisRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(default='female', max_length=20)),
                ('bust_inches', models.FloatField(blank=True, null=True)),
                ('waist_inches', models.FloatField(blank=True, null=True)),
                ('hip_inches', models.FloatField(blank=True, null=True)),
                ('high_hip_inches', models.FloatField(blank=True, null=True)),
                ('predicted_shape', models.CharField(max_length=50)),
                ('confidence', models.FloatField(default=0.95)),
                ('recommendations', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='body_analyses', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
